# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  # ========================================================================
  #                          Mandatory variables 
  # ========================================================================
 # Update Azure.ResourceGroupName value with Azure resource group name.
  Azure.ResourceGroupName: 'restairline-group'

  # Update Azure.ServiceConnectionId value with AzureRm service endpoint.
  Azure.ServiceConnectionId: 'Visual Studio Enterprise(8e5414cf-26ac-43c3-bac4-3e9235fbcbda)'

  # Update Azure.Location value with Azure Location.
  Azure.Location: 'eastasia'

  # Update ACR.Name value with ACR name. Please note ACR names should be all lower-case and alphanumeric only.
  ACR.Name: 'restairline'
  
  # Update Web.Name value with a name that identifies your new Web app. Valid characters are a-z, 0-9, and -.
  WebApp.Name: 'restairline-test'
  
  # Update ServicePlan.Name value with a name of the app service plan.
  ServicePlan.Name: '{{#toAlphaNumericString repositoryName 45}}{{/toAlphaNumericString}}-plan'

  # ========================================================================
  #                           Optional variables 
  # ========================================================================
  
  ACR.ImageName: '$(ACR.Name):$(Build.BuildId)'
  ACR.FullName: '$(ACR.Name).azurecr.io'
  System.Debug: 'false'


steps:
  - bash: printenv | sort

  - task: Bash@3
    displayName: Build
    inputs:
      filePath: './buildscript/build.bash'

#  - task: Bash@3
#    displayName: Unit test
#    inputs:
#      filePath: './buildscript/unitTest.bash'

  - task: Bash@3
    displayName: Push image
    inputs:
      filePath: './buildscript/push.bash'      

  - task: Bash@3
    displayName: Deploy to test
    inputs:
      filePath: './buildscript/deployappservice.bash'      