apiVersion: apps/v1 
kind: Deployment
metadata:
  name: restairline-api
  labels:
    app: restairline
    tier: backend
spec:
  selector:
    matchLabels:
      app: restairline
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: restairline 
        tier: backend
    spec:
      containers:
        - name: restairline-api
          image: restairlinetest.azurecr.io/restairline:v1
          imagePullPolicy: Always
          env:
            - name: EventStoreConnectionString
              valueFrom:
                configMapKeyRef:
                  name: externalcfg
                  key: EventStoreConnectionString
            - name: ReadModelConnectionString
              valueFrom:
                configMapKeyRef:
                  name: externalcfg
                  key: ReadModelConnectionString
            - name: OrchestratorType
              value: 'K8S'
            - name: ASPNETCORE_ENVIRONMENT
              value: Test 
          ports:
            - containerPort: 80

      imagePullSecrets:
        - name: registry-key
---
apiVersion: v1
kind: Service
metadata:
  name: restairline-api
  labels:
    app: restairline
    tier: backend
spec:
  # comment or delete the following line if you want to use a LoadBalancer
  # type: NodePort
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: restairline
    tier: backend

